Repository BraveDroid/NavigationPlayground, pull requests merged in 2020-01, with the labels that each got.

#18 [eng-17] fix RF assignee #17
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/engineering-issue-template.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Engineering Task

#25 [nav-15] conditional navigation
  app/build.gradle
  app/src/main/java/com/bravedroid/navigation/LoginFragment.kt
  app/src/main/java/com/bravedroid/navigation/LoginViewModel.kt
  app/src/main/java/com/bravedroid/navigation/MainActivity.kt
  app/src/main/java/com/bravedroid/navigation/ProfileFragment.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: enhancement

#28 [BUG] fix the automating closing of issues
  .github/pull_request_template.md
Labels: bug

#29 [nav-27] simplify the onbackpressed behavior
  app/src/main/java/com/bravedroid/navigation/MainActivity.kt
  app/src/main/java/com/bravedroid/navigation/ProfileFragment.kt
Labels: enhancement

#30 [BUG] triger the ci on pull_request
  .github/workflows/pipeline.yml
Labels: bug

#33 [BUG-11] support navigation and pass arguments data using safe args/ bundle
  app/build.gradle
  app/src/main/java/com/bravedroid/navigation/AboutActivity.kt
  app/src/main/java/com/bravedroid/navigation/ChooseRecipientFragment.kt
  app/src/main/java/com/bravedroid/navigation/ConfirmationFragment.kt
  app/src/main/java/com/bravedroid/navigation/InfoFragment.kt
  app/src/main/java/com/bravedroid/navigation/MainFragment.kt
  app/src/main/java/com/bravedroid/navigation/MessagesFragment.kt
  app/src/main/java/com/bravedroid/navigation/SpecifyAmountFragment.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/fragment_confirmation.xml
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/layout/fragment_messages.xml
  app/src/main/res/navigation/message_nav_graph.xml
  app/src/main/res/navigation/nav_graph.xml
  historymodule/build.gradle
  historymodule/src/main/java/com/bravedroid/historymodule/HistoryFragment.kt
  historymodule/src/main/res/layout/fragment_history.xml
Labels: bug

#44 [nav-23] animate transitions between destinations
  app/src/main/java/com/bravedroid/navigation/AboutActivity.kt
  app/src/main/java/com/bravedroid/navigation/ChooseRecipientFragment.kt
  app/src/main/java/com/bravedroid/navigation/MainActivity.kt
  app/src/main/java/com/bravedroid/navigation/MainFragment.kt
  app/src/main/java/com/bravedroid/navigation/SettingsFragment.kt
  app/src/main/java/com/bravedroid/navigation/SpecifyAmountFragment.kt
  app/src/main/java/com/bravedroid/navigation/util/NavigationDecorator.kt
  app/src/main/res/anim/slide_in_from_left_to_right.xml
  app/src/main/res/anim/slide_in_from_right_to_left.xml
  app/src/main/res/anim/slide_out_from_left_to_right.xml
  app/src/main/res/anim/slide_out_from_right_to_left.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/fragment_main.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/main_nav_graph.xml
Labels: enhancement

#43 [NAV-22] Support Deep Linking
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bravedroid/navigation/AboutActivity.kt
  app/src/main/java/com/bravedroid/navigation/InfoFragment.kt
  app/src/main/java/com/bravedroid/navigation/MainFragment.kt
  app/src/main/java/com/bravedroid/navigation/SettingsFragment.kt
  app/src/main/java/com/bravedroid/navigation/SpecifyAmountFragment.kt
  app/src/main/java/com/bravedroid/navigation/util/DeepLinkFactory.kt
  app/src/main/java/com/bravedroid/navigation/util/NotificationFactory.kt
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_specify_amount.xml
  app/src/main/res/navigation/main_nav_graph.xml
  history-feature/.gitignore
  history-feature/build.gradle
  history-feature/consumer-rules.pro
  history-feature/proguard-rules.pro
  history-feature/src/androidTest/java/com/bravedroid/historymodule/ExampleInstrumentedTest.kt
  history-feature/src/main/AndroidManifest.xml
  history-feature/src/main/java/com/bravedroid/historymodule/HistoryFragment.kt
  history-feature/src/main/res/layout/fragment_history.xml
  history-feature/src/main/res/navigation/history_nav_graph.xml
  history-feature/src/main/res/values/colors.xml
  history-feature/src/main/res/values/strings.xml
  history-feature/src/test/java/com/bravedroid/historymodule/ExampleUnitTest.kt
  historymodule/src/main/java/com/bravedroid/historymodule/HistoryFragment.kt
  settings.gradle
Labels: enhancement

#45 [nav-35] Add unit test to navigation
  app/build.gradle
  app/src/androidTest/java/com/bravedroid/navigation/ChooseRecipientFragmentTest.kt
  app/src/androidTest/java/com/bravedroid/navigation/ConfirmationFragmentTest.kt
  app/src/androidTest/java/com/bravedroid/navigation/MainFragmentTest.kt
  app/src/androidTest/java/com/bravedroid/navigation/SpecifyAmountFragmentTest.kt
  app/src/androidTest/java/com/bravedroid/navigation/ViewBalanceFragmentTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/bravedroid/navigation/ChooseRecipientFragment.kt
  app/src/main/java/com/bravedroid/navigation/MainFragment.kt
  app/src/main/java/com/bravedroid/navigation/ViewBalanceFragment.kt
  app/src/main/java/com/bravedroid/navigation/util/ActivityTransitionUtilJava.java
  app/src/main/java/com/bravedroid/navigation/util/GlobalTransitionUtilJava.java
  app/src/main/java/com/bravedroid/navigation/util/NavigationDecorator.kt
  app/src/main/java/com/bravedroid/navigation/util/Testing.kt
  app/src/main/res/layout/fragment_choose_recipient.xml
  app/src/main/res/layout/fragment_view_balance.xml
  app/src/main/res/values/styles.xml
  build.gradle
  history-feature/build.gradle
Labels: enhancement

#46 [bugfix] make view scrollable when the keyboard appears
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_login.xml
Labels: bug

#48 [Bugfix]Fix snackbar error
  app/build.gradle
  app/src/main/java/com/bravedroid/navigation/ChooseUserPasswordFragment.kt
  history-feature/build.gradle
Labels: bug
